#!/usr/bin/env node
"use strict";var H=Object.create;var g=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var w=Object.getOwnPropertyNames;var $=Object.getPrototypeOf,j=Object.prototype.hasOwnProperty;var O=(n,e,t,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of w(e))!j.call(n,i)&&i!==t&&g(n,i,{get:()=>e[i],enumerable:!(r=v(e,i))||r.enumerable});return n};var f=(n,e,t)=>(t=n!=null?H($(n)):{},O(e||!n||!n.__esModule?g(t,"default",{value:n,enumerable:!0}):t,n));var a=f(require("fs")),l=f(require("path"));var u=[{key:"connect",title:"Connect",blurb:"Bind this project to a ContextDX board"},{key:"map",title:"Map",blurb:"Turn the %DOMAIN% into a living board (%DOMAIN% \u2192 board)"},{key:"understand",title:"Understand",blurb:"Run intelligence on the mapped board"},{key:"build",title:"Build",blurb:"Build from the platform's spec \u2014 compiled skills, intents, board design (platform \u2192 %DOMAIN%)"},{key:"operate",title:"Operate",blurb:"Keep production and the board in a scheduled loop"}];function M(n){return n.includes("work")?"document set":"codebase"}function h(n){return n.replace(/\|/g,"\\|")}function R(n){let e=u.map(t=>t.title).join("|");return n.replace(new RegExp(`^(?:${e}) \xB7 `),"")}function y(n,e,t){t.push("| Command | Arguments | Description |"),t.push("| ------- | --------- | ----------- |");for(let r of e){let i=r.argumentHint?`\`${h(r.argumentHint)}\``:"\u2014";t.push(`| \`/${n}:${r.name}\` | ${i} | ${h(R(r.description))} |`)}t.push("")}function b(n,e){let t=M(n.name),r=[...e].sort((s,p)=>s.name.localeCompare(p.name)),c=new Set(r.map(s=>s.name)).has("analyze-docs")?"analyze-docs":"analyze",o=[`# ${n.name} v${n.version}`,""];n.description&&o.push(n.description,"");let x=new Set(u.map(s=>s.key));u.forEach((s,p)=>{let m=r.filter(S=>S.category===s.key);m.length!==0&&(o.push(`## ${p+1} \xB7 ${s.title} \u2014 ${s.blurb.replace(/%DOMAIN%/g,t)}`,""),y(n.name,m,o))});let d=r.filter(s=>s.category===null||!x.has(s.category));return d.length>0&&(o.push("## Other",""),y(n.name,d,o)),o.push(`> **Where to start:** existing ${t}? begin at **Map**. Empty project with compiled skills from your platform app? begin at **Build**.`),o.push(`> **The loop:** monitoring signals and analyses become insights; architects promote them to intents; \`/intents\` implements them; \`/${c}\` + \`/sync\` verify the change on the board.`),o.push('> **Opting out of source references:** synced nodes and edges include file-path source references (and links into your git host) by default. To omit them from what `/sync` pushes, set `"includeSourceReferences": false` in `.contextdx/config.json`.'),o.join(`
`)}function I(){let n=process.argv.slice(2),e={pluginRoot:l.resolve(__dirname,"..")};for(let t=0;t<n.length;t++)switch(n[t]){case"--plugin-root":e.pluginRoot=l.resolve(n[++t]);break;case"--help":console.log(`
CodePlugin Help CLI

Lists every slash command in the plugin with its description, plus the
plugin name + version from .claude-plugin/plugin.json.

Usage: node cdx-help.js [options]

Options:
  --plugin-root <path>  Override the plugin root (default: dirname/..)
  --help                Show this help message

Output: ready-to-display markdown to stdout
`),process.exit(0)}return e}function C(n){let e={},t=n.split(/\r?\n/);if(t[0]?.trim()!=="---")return e;for(let r=1;r<t.length;r++){let i=t[r];if(i.trim()==="---")break;let c=i.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(!c)continue;let o=c[2].trim();o.length>=2&&(o.startsWith('"')&&o.endsWith('"')||o.startsWith("'")&&o.endsWith("'"))&&(o=o.slice(1,-1)),e[c[1]]=o}return e}var k=[".claude-plugin",".codex-plugin",".cursor-plugin"];function A(n){for(let e of k){let t=l.join(n,e,"plugin.json");if(a.existsSync(t))try{return JSON.parse(a.readFileSync(t,"utf-8"))}catch{return null}}return null}function F(n){let e=l.join(n,"commands");return a.existsSync(e)?a.readdirSync(e).filter(t=>t.endsWith(".md")).map(t=>{let r=a.readFileSync(l.join(e,t),"utf-8"),i=C(r);return{name:l.basename(t,".md"),description:i.description??"(no description)",argumentHint:i["argument-hint"]||null,category:i.category||null}}):L(l.join(n,"skills"))}function L(n){return a.existsSync(n)?a.readdirSync(n,{withFileTypes:!0}).filter(e=>e.isDirectory()).flatMap(e=>{let t=l.join(n,e.name,"SKILL.md");if(!a.existsSync(t))return[];let r=C(a.readFileSync(t,"utf-8"));return[{name:r.name||e.name,description:r.description??"(no description)",argumentHint:r["argument-hint"]||null,category:r.category||null}]}):[]}function P(){let n=I(),e=A(n.pluginRoot);e||(console.log(`Could not read plugin manifest (${k.join("|")}/plugin.json) under ${n.pluginRoot}`),process.exit(1));let t={name:e.name??"(unknown)",version:e.version??"(unknown)",description:e.description??""};console.log(b(t,F(n.pluginRoot))),process.exit(0)}P();
