#!/usr/bin/env node
"use strict";var S=Object.create;var m=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var w=Object.getOwnPropertyNames;var O=Object.getPrototypeOf,$=Object.prototype.hasOwnProperty;var j=(n,e,t,o)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of w(e))!$.call(n,i)&&i!==t&&m(n,i,{get:()=>e[i],enumerable:!(o=v(e,i))||o.enumerable});return n};var g=(n,e,t)=>(t=n!=null?S(O(n)):{},j(e||!n||!n.__esModule?m(t,"default",{value:n,enumerable:!0}):t,n));var a=g(require("fs")),l=g(require("path"));var f=[{key:"connect",title:"Connect",blurb:"Bind this project to a ContextDX board"},{key:"map",title:"Map",blurb:"Turn the %DOMAIN% into a living board (%DOMAIN% \u2192 board)"},{key:"understand",title:"Understand",blurb:"Run intelligence on the mapped board"},{key:"build",title:"Build",blurb:"Build from the platform's spec \u2014 compiled skills, intents, board design (platform \u2192 %DOMAIN%)"},{key:"operate",title:"Operate",blurb:"Keep production and the board in a scheduled loop"}];function M(n){return n.includes("work")?"document set":"codebase"}function h(n){return n.replace(/\|/g,"\\|")}function y(n,e,t){t.push("| Command | Arguments | Description |"),t.push("| ------- | --------- | ----------- |");for(let o of e){let i=o.argumentHint?`\`${h(o.argumentHint)}\``:"\u2014";t.push(`| \`/${n}:${o.name}\` | ${i} | ${h(o.description)} |`)}t.push("")}function b(n,e){let t=M(n.name),o=[...e].sort((s,p)=>s.name.localeCompare(p.name)),c=new Set(o.map(s=>s.name)).has("analyze-docs")?"analyze-docs":"analyze",r=[`# ${n.name} v${n.version}`,""];n.description&&r.push(n.description,"");let x=new Set(f.map(s=>s.key));f.forEach((s,p)=>{let d=o.filter(H=>H.category===s.key);d.length!==0&&(r.push(`## ${p+1} \xB7 ${s.title} \u2014 ${s.blurb.replace(/%DOMAIN%/g,t)}`,""),y(n.name,d,r))});let u=o.filter(s=>s.category===null||!x.has(s.category));return u.length>0&&(r.push("## Other",""),y(n.name,u,r)),r.push(`> **Where to start:** existing ${t}? begin at **Map**. Empty project with compiled skills from your platform app? begin at **Build**.`),r.push(`> **The loop:** monitoring signals and analyses become insights; architects promote them to intents; \`/intents\` implements them; \`/${c}\` + \`/sync\` verify the change on the board.`),r.push('> **Opting out of source references:** synced nodes and edges include file-path source references (and links into your git host) by default. To omit them from what `/sync` pushes, set `"includeSourceReferences": false` in `.contextdx/config.json`.'),r.join(`
`)}function I(){let n=process.argv.slice(2),e={pluginRoot:l.resolve(__dirname,"..")};for(let t=0;t<n.length;t++)switch(n[t]){case"--plugin-root":e.pluginRoot=l.resolve(n[++t]);break;case"--help":console.log(`
CodePlugin Help CLI

Lists every slash command in the plugin with its description, plus the
plugin name + version from .claude-plugin/plugin.json.

Usage: node cdx-help.js [options]

Options:
  --plugin-root <path>  Override the plugin root (default: dirname/..)
  --help                Show this help message

Output: ready-to-display markdown to stdout
`),process.exit(0)}return e}function C(n){let e={},t=n.split(/\r?\n/);if(t[0]?.trim()!=="---")return e;for(let o=1;o<t.length;o++){let i=t[o];if(i.trim()==="---")break;let c=i.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(!c)continue;let r=c[2].trim();r.length>=2&&(r.startsWith('"')&&r.endsWith('"')||r.startsWith("'")&&r.endsWith("'"))&&(r=r.slice(1,-1)),e[c[1]]=r}return e}var k=[".claude-plugin",".codex-plugin",".cursor-plugin"];function R(n){for(let e of k){let t=l.join(n,e,"plugin.json");if(a.existsSync(t))try{return JSON.parse(a.readFileSync(t,"utf-8"))}catch{return null}}return null}function A(n){let e=l.join(n,"commands");return a.existsSync(e)?a.readdirSync(e).filter(t=>t.endsWith(".md")).map(t=>{let o=a.readFileSync(l.join(e,t),"utf-8"),i=C(o);return{name:l.basename(t,".md"),description:i.description??"(no description)",argumentHint:i["argument-hint"]||null,category:i.category||null}}):F(l.join(n,"skills"))}function F(n){return a.existsSync(n)?a.readdirSync(n,{withFileTypes:!0}).filter(e=>e.isDirectory()).flatMap(e=>{let t=l.join(n,e.name,"SKILL.md");if(!a.existsSync(t))return[];let o=C(a.readFileSync(t,"utf-8"));return[{name:o.name||e.name,description:o.description??"(no description)",argumentHint:o["argument-hint"]||null,category:o.category||null}]}):[]}function L(){let n=I(),e=R(n.pluginRoot);e||(console.log(`Could not read plugin manifest (${k.join("|")}/plugin.json) under ${n.pluginRoot}`),process.exit(1));let t={name:e.name??"(unknown)",version:e.version??"(unknown)",description:e.description??""};console.log(b(t,A(n.pluginRoot))),process.exit(0)}L();
